FROM golang:1.18-alpine

WORKDIR /kitchens
COPY ./.koksmat/kitchenroot .
WORKDIR /kitchens/magic-query
COPY . .  
WORKDIR /kitchens/magic-query/.koksmat/api

RUN go install

EXPOSE 8080

CMD [ "sleep","infinity"]
