// -------------------------------------------------------------------
// Generated by 365admin-publish
// Service wrapper  v1
// -------------------------------------------------------------------
/*
---
title: List Groups
---
*/
package services

import (
	"log"

	nats "github.com/nats-io/nats.go"
	"github.com/spf13/viper"
)

func callMicroservice() error {
	var nc *nats.Conn

	natsServer := viper.GetString("NATS")
	if natsServer == "" {
		natsServer = "nats://127.0.0.1:4222"
	}
	log.Println("Connecting to", natsServer)
	nc, err := nats.Connect(natsServer)
	defer nc.Close()
	if err != nil {
		return err
	}
	return nil
}
